### ISSUE TITLE
Por favor, deixar as imagens prontas no Docker Hub

### ISSUE THREAD

**Issue by zanfranceschi** [leandronsp/rinha-backend-ruby#1]
meu mano, por favor, coloca a imagem das APIs num docker hub, pls. é inviável pra mim buildar tudo que chega.

**Comment by leandronsp** [comment]
opa, já deixei amigão, repo atualizado e docker hub devidamente com a imagem:

https://hub.docker.com/r/leandronsp/rinha-backend-ruby
